### ISSUE TITLE
OpenGL

### ISSUE THREAD

**Issue by joflashstudios** [jazzkutya/ksp-fullscreenfix#1]
Is there a way to make the same change for OpenGL? (-force-opengl) A lot of people (myself included) rely on OpenGL to allow us to stay under 4GB.

http://forum.kerbalspaceprogram.com/threads/84203-Less-memory-usage-by-using-OpenGL

**Comment by jazzkutya** [comment]
it seems to me that KSP with -force-opengl already runs in exlusive fullscreen mode on windows 7 with aero disabled. What OS are you using?

**Comment by jazzkutya** [comment]
silly me, opengl is the only possibility on every OS except windows. So more important question is, what problem do you have you think my patcher could solve?

**Comment by joflashstudios** [comment]
What made me think that it didn't work for OpenGL is this:

Nvidia ShadowPlay:
Doesn't work in vanilla Direct3D
Doesn't work in vanilla OpenGL

I determined this was because it wasn't running in true full screen. So, after installing your mod, Nvidia ShadowPlay:
Works with Direct3D
Still doesn't work with OpenGL

I assumed (perhaps wrongly) based on this that your code puts the game in true full screen with Direct3D, but doesn't work for OpenGL.

**Comment by jazzkutya** [comment]
as far as i know shadowplay supports opengl ONLY with desktop recording, for that you need a borderless fullscreen window (exact opposite of true fullscreen), search the KSP forums (so this means true fullscreen mode for d3d but borderless window mode for opengl).

Anyway you are right, my patch does not do anything with OpenGL, but KSP on windows and opengl is using true fullscreen mode even without my patch.
