### ISSUE TITLE
KSP 1.1 Support

### ISSUE THREAD

**Issue by csmith105** [jazzkutya/ksp-fullscreenfix#3]
Hello,

Any change this can be updated to include the newest build of KSP 1.1?

**Comment by jazzkutya** [comment]
I think there is a good chance, but you have to wait - I'm literally stuck in linux since a couple of days trying to save data from a hard disk infected with bad sectors. 19GB copied in 4 days :). Will probably give up in a couple of days later and will be able to see 1.1 on windows.

**Comment by csmith105** [comment]
Sorry to hear that. :( No hurry, thanks man!

**Comment by jazzkutya** [comment]
If you can use a hex editor see the first post in the forum thread. I updated it with info on 1.1.1183. The patcher has to be updated to handle 64 bit too but I don't feel like doing it yet with a cheap excuse of KSP 1.1 being a prerelease :) But it will happen eventually, my bet is on the weekend.

**Comment by jazzkutya** [comment]
The forum thread is over [here ](http://forum.kerbalspaceprogram.com/index.php?/topic/103537-ksp-10x-090-windows-true-exclusive-fullscreen-shadowplay-and-gsync-solution/)

**Comment by jazzkutya** [comment]
New patcher released, now supports KSP 1.1.0 (64bit only)
